[package]
name = "bb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
crossterm = "0.29"
log = { version = "0.4", features = ["std"] }
ratatui = "0.29"
tokio = { version = "1.46", features = ["full"] }
