[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
log = { version = "0.4", features = ["std"] }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }


