[package]
name = "bb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bluer = { version = "0.17.4", features = ["full"] }
crossterm = "0.29.0"
log = { version = "0.4.27", features = ["std"] }
ratatui = "0.29.0"
tokio = { version = "1.46.1", features = ["full"] }
