[package]
name = "bb-server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64ct = "1.6.0"
bb-tui = { version = "0.1.0", path = "../bb-tui" }
log.workspace = true
rand = "0.8.5"
rusqlite = "0.37.0"
russh = "0.53.0"
tokio.workspace = true
