[package]
name = "bb"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
log.workspace = true
bb-server = { version = "0.1.0", path = "../bb-server" }


